services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lighthouse-backend-challenge
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - lighthouse-backend-challenge-network

volumes:
  postgres-data:

networks:
  lighthouse-backend-challenge-network:
    driver: bridge
